spring.application.name=veterinaria

# Configuración de base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (Crea y actualiza las tablas automáticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
